name: Release Version
on:
  push:
    tags:
      - '*'

jobs:
  builder:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - arch: x64
            distro: ubuntu-latest
          - arch: aarch64
            distro: ubuntu-latest
          - arch: armv7
            distro: ubuntu-latest
          - arch: aarch64
            distro: fedora_latest
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: |
          go build -gcflags '-trimpath' -ldflags "-s -w -X main.version=${GITHUB_REF_NAME} -X main.commit=${GITHUB_SHA}"
        workdir: cmd/terraform-provider-skopeo
  goreleaser:
    needs: builder
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          workdir: cmd/terraform-provider-skopeo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
