name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          go build -tags containers_image_openpgp
        working-directory: cmd/terraform-provider-skopeo
